INSERT INTO CURRENCY_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE) VALUES (10001, 'USD', 'INR', 65)
INSERT INTO CURRENCY_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE) VALUES (10002, 'EUR', 'INR', 80)
INSERT INTO CURRENCY_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE) VALUES (10003, 'AUS', 'INR', 50)
INSERT INTO CURRENCY_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE) VALUES (10004, 'POUND', 'INR', 100)